version: '3'

services:
  app:
    container_name: adv_buyer_python_userbot
    build: .
    ports:
      - 10321:10321
    restart: unless-stopped
    environment:
      PORT: 10321
      PG_URL: postgresql://postgres:1q2w3e4r@db/monitoring1
    networks:
      - mynet
      - malone_7

  db:
    container_name: adv_buyer_python_userbot_db
    image: postgres:15-alpine
    ports:
      - 10322:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: monitoring1
    networks:
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge
  malone_7:
    external: true